<?php

/**
 * @file
 * Main file for ac_ffmpeg module.
 */

use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_theme().
 */
function ac_ffmpeg_theme($existing, $type, $theme, $path) {
  return [
    'html5_ffmpeg' => [
    'variables' => ['video_url' => NULL],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ac_ffmpeg_node_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'lecture') {
    // Lecture Body parsing.
    $body = $entity->get('field_text')->value;
    $body_words = preg_split('/[\s]+/', $body);
    // Collect words videos.
    $videos = [];
    foreach ($body_words as $body_word) {
      // Query database to get word video.
      $query = \Drupal::entityQuery('node');
      $query
        ->condition('type', 'word')
        ->condition('title', $body_word)
        ->condition('status', 1)
        ->range(0,1);
      $results = $query->execute();
      if ($results) {
        $nid = array_keys($results)[0];
        $node = Node::load($nid);
        $video_target_id = $node->get('field_video')->target_id;
        $media = File::load($video_target_id);
        $video_uri = $media->getFileUri();
        $video = \Drupal::service('file_system')
          ->realpath($video_uri);
        $videos[] = $video;
      }
    }
    $entity->set('field_video_url', '');
    if ($videos) {
      // Then merge videos.
      $video_merger = \Drupal::service('ac_ffmpeg.video_merger');
      $built_video = $video_merger->concateVideos($videos, $entity->id());
      // save built video
      $entity->set('field_video_url', $built_video);
    }
    
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ac_ffmpeg_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'lecture') {
    $built_video = $entity->get('field_video_url')->value;
    if ($built_video) {
      $build['output_video'] = [
        '#theme' => 'html5_ffmpeg',
        '#video_url' => $built_video,
      ];
    }
  }
}
